### ISSUE TITLE
Windows OR Super Key Bug

### ISSUE THREAD

**Issue by TheLinuxGuy-ssh** [excalith/.dotfiles#2]
**Describe the bug**
So recently 1-2 weeks ago i got your dotfiles and implemented them on my Ubuntu Linux OS, but after 2-3 i notcied that my windows or Super_L key was not working if i wanted to go to the applications menu in linux, i have tried multiple ways for fixing that but nowi suppose i need help from Excalith AKA can cellek himself...

As you can see below, the keycode "133" key is supposed to be my super_L key but after implementing the dotfiles, it changed to Control, any fix??

![image](https://user-images.githubusercontent.com/107614947/234223153-4f449a79-9eda-49e3-b967-594ad2917711.png)

**Comment by excalith** [comment]
Hey @rohansharma-developer,

The [setup_defaults.sh](https://github.com/excalith/.dotfiles/blob/main/system/ubuntu/setup_defaults.sh) also does some keybinding adjustments the way I prefer using. Have a look at the binding changes from line 61 to 91 of *Key Bindings* section. 

In order to change the default behaviour,  go to `Settings > Keyboard > Keyboard Shortcuts` should have all the shortcuts listed there. You can either
- Change the one you want
- Use `Reset All` button to revert it back to default shortcuts

As for dotfiles, they are meant to be forked and adjusted as you feel fit. There are even more complex changes on other dotfiles, so reading through the setup code first is highly recommended. Just in case I wanted to point it out 🙏
